#!/usr/bin/env python3

import sys, tkinter

from tc import producer, viewer, server

if len(sys.argv) == 1:
    master = tkinter.Tk()
    master.title('Telecorpo')

    def command(func):
        def inner():
            master.destroy()
            func()
        return inner

    producer_btn = tkinter.Button(master, text='Producer', command=command(producer.main))
    producer_btn.pack(expand=True, fill='both')
    
    viewer_btn = tkinter.Button(master, text='Viewer', command=command(viewer.main))
    viewer_btn.pack(expand=True, fill='both')

    master.mainloop()

if len(sys.argv) == 2:
    module = sys.argv[1]
    if module == 'server':
        server.main()
    elif module == 'viewer':
        viewer.main()
    elif module == 'producer':
        producer.main()
    else:
        print('Error: module %s not found' % module)

